### ISSUE TITLE
ルビ(ruby)タグに対応したい

### ISSUE THREAD

**Issue by L1n4r1A** [L1n4r1A/t2h#1]
ルビタグは乱用するものではないが、小説を書くにおいては必要不可欠とも言える機能である。
また、ePubを作成する際にもルビタグは有能なのでつけれるようにしたい。(ePubでは<br>ではなく<br />だがまぁいい)

記法
`抽斗《ひきだし》`→`<ruby>抽斗<rt>ひきだし</rt></ruby>`が一番スマート(青空文庫記法)
無理であれば`｜抽斗《ひきだし》`で代用する(それが一番安全かも知れない)

**Comment by cffnpwr** [comment]
これやった

**Comment by L1n4r1A** [comment]
🙏
